--- # Start webserver
-  hosts:  webserver
   become: yes
   gather_facts: yes
   tasks:
   -  debug:
        var: target_service
   -  name: install apache
      yum:
        name: "{{ target_service }}"
        state: latest
      notify: 
        -  restart httpd
   -  name: create index
      file: 
        name: /var/www/html/index.html
        state: touch
   -  name: add web content
      lineinfile:
        path: /var/www/html/index.html
        line: "{{ ansible_hostname }}"
      notify:
        -  restart httpd  
      register: task_debug
   -  debug:
        msg: "output line is : {{ task_debug }}"
   handlers:
   -  name : attempt start httpd    
      service:
        name: httpd
        state: restarted
      listen: "restart httpd"
            
