--- # Start webserver
-  hosts:  webserver
   become: yes

   tasks:
     -  name: latest httpd installed
        yum:
          name: httpd
          state: latest
     -  name: create index
        file: 
          name: /var/www/html/index.html
          state: touch
     -  name: add web content
        lineinfile:
          path: /var/www/html/index.html
          line: 'felix curso 2'
     -  name : permisos index    
        file:
          path: /var/www/html/index.html
          owner: root
          group: root
          mode: 01755           
